export const SHOW_MODAL = 'APP/SHOW_MODAL';
export const HIDE_MODAL = 'APP/HIDE_MODAL';
export const SHOW_REGISTRATION_FORM = 'APP/SHOW_REGISTRATION_FORM';
export const SHOW_LOG_IN_FORM = 'APP/SHOW_LOG_IN_FORM';
